import { LockKeyhole, Mail, Store, UserRound } from 'lucide-react'
import { useState } from 'react'
import { Link, Navigate, useNavigate, useSearchParams } from 'react-router-dom'
import { useAuth } from '../features/auth/AuthContext'
import { api, csrfCookie, errorMessage } from '../lib/api'
import type { ApiEnvelope, Session } from '../types/api'

export function LoginPage() {
  const { login, session } = useAuth(); const navigate = useNavigate(); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [remember, setRemember] = useState(true); const [error, setError] = useState(''); const [submitting, setSubmitting] = useState(false)
  if (session) return <Navigate to="/app" replace />
  async function submit(event: React.FormEvent) { event.preventDefault(); setSubmitting(true); setError(''); try { await login({ email, password, remember }); navigate('/app') } catch (err) { setError(errorMessage(err)) } finally { setSubmitting(false) } }
  return <AuthLayout title="Welcome back" text="Sign in to manage your restaurant."><form onSubmit={submit} className="auth-form"><Field icon={<Mail size={17} />} label="Email address"><input required value={email} onChange={(event) => setEmail(event.target.value)} type="email" placeholder="owner@hotel.com" /></Field><Field icon={<LockKeyhole size={17} />} label="Password"><input required value={password} onChange={(event) => setPassword(event.target.value)} type="password" placeholder="Your password" /></Field>{error && <p className="form-error">{error}</p>}<div className="auth-option-row"><label className="check-row"><input type="checkbox" checked={remember} onChange={(event) => setRemember(event.target.checked)} />Keep me signed in</label><Link to="/forgot-password">Forgot password?</Link></div><button className="button button-primary button-full" disabled={submitting}>{submitting ? 'Signing in…' : 'Sign in'}</button><p className="auth-footer">Setting up a new restaurant? <Link to="/setup">Create the first owner account</Link></p></form></AuthLayout>
}

export function ForgotPasswordPage() {
  const [email, setEmail] = useState(''); const [error, setError] = useState(''); const [sent, setSent] = useState(false); const [submitting, setSubmitting] = useState(false)
  async function submit(event: React.FormEvent) { event.preventDefault(); setSubmitting(true); setError(''); try { await csrfCookie(); await api.post('/api/v1/forgot-password', { email }); setSent(true) } catch (err) { setError(errorMessage(err)) } finally { setSubmitting(false) } }
  return <AuthLayout title="Reset your password" text="Enter your email and we’ll send a secure reset link."><form onSubmit={submit} className="auth-form"><Field icon={<Mail size={17} />} label="Email address"><input required type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="owner@hotel.com" /></Field>{error && <p className="form-error">{error}</p>}{sent && <p className="form-success"><CheckIcon />If the account exists, a reset link has been sent.</p>}<button className="button button-primary button-full" disabled={submitting}>{submitting ? 'Sending…' : 'Send reset link'}</button><p className="auth-footer"><Link to="/login">Back to sign in</Link></p></form></AuthLayout>
}

export function ResetPasswordPage() {
  const [params] = useSearchParams(); const [email, setEmail] = useState(''); const [token, setToken] = useState(params.get('token') ?? ''); const [password, setPassword] = useState(''); const [confirmation, setConfirmation] = useState(''); const [error, setError] = useState(''); const [done, setDone] = useState(false); const [submitting, setSubmitting] = useState(false)
  async function submit(event: React.FormEvent) { event.preventDefault(); setSubmitting(true); setError(''); try { await csrfCookie(); await api.post('/api/v1/reset-password', { email, token, password, password_confirmation: confirmation }); setDone(true) } catch (err) { setError(errorMessage(err)) } finally { setSubmitting(false) } }
  return <AuthLayout title="Choose a new password" text="Use a strong password with letters and numbers."><form onSubmit={submit} className="auth-form"><Field icon={<Mail size={17} />} label="Email address"><input required type="email" value={email} onChange={(event) => setEmail(event.target.value)} /></Field><Field icon={<LockKeyhole size={17} />} label="Reset token"><input required value={token} onChange={(event) => setToken(event.target.value)} /></Field><Field icon={<LockKeyhole size={17} />} label="New password"><input required minLength={8} type="password" value={password} onChange={(event) => setPassword(event.target.value)} /></Field><Field icon={<LockKeyhole size={17} />} label="Confirm password"><input required minLength={8} type="password" value={confirmation} onChange={(event) => setConfirmation(event.target.value)} /></Field>{error && <p className="form-error">{error}</p>}{done && <p className="form-success"><CheckIcon />Password reset. You can now sign in.</p>}<button className="button button-primary button-full" disabled={submitting}>{submitting ? 'Saving…' : 'Reset password'}</button><p className="auth-footer"><Link to="/login">Back to sign in</Link></p></form></AuthLayout>
}

export function OnboardingPage() {
  const { session, setSession } = useAuth(); const navigate = useNavigate(); const [error, setError] = useState(''); const [submitting, setSubmitting] = useState(false); const [form, setForm] = useState({ hotel_name: '', outlet_name: 'Main Restaurant', outlet_code: 'MAIN', owner_name: '', owner_email: '', password: '', password_confirmation: '' })
  if (session) return <Navigate to="/app" replace />
  const change = (key: keyof typeof form) => (event: React.ChangeEvent<HTMLInputElement>) => setForm({ ...form, [key]: event.target.value })
  async function submit(event: React.FormEvent) { event.preventDefault(); setError(''); setSubmitting(true); try { await csrfCookie(); const response = await api.post<ApiEnvelope<{ user: Session['user']; hotel: Session['hotel']; outlet: Session['outlets'][number] }>>('/api/v1/onboarding', form); setSession({ user: response.data.data.user, hotel: response.data.data.hotel, role: { id: 0, name: 'Owner', slug: 'owner', is_owner: true }, permissions: ['*'], outlets: [response.data.data.outlet], hotel_wide_outlet_access: true }); navigate('/app') } catch (err) { setError(errorMessage(err)) } finally { setSubmitting(false) } }
  return <AuthLayout title="Set up your restaurant" text="Create the first Owner account, hotel and outlet."><form onSubmit={submit} className="auth-form setup-form"><Field icon={<Store size={17} />} label="Hotel name"><input required value={form.hotel_name} onChange={change('hotel_name')} placeholder="Aswad Restaurant" /></Field><Field icon={<Store size={17} />} label="First outlet"><input required value={form.outlet_name} onChange={change('outlet_name')} /></Field><Field icon={<Store size={17} />} label="Outlet code"><input required value={form.outlet_code} onChange={change('outlet_code')} /></Field><Field icon={<UserRound size={17} />} label="Owner name"><input required value={form.owner_name} onChange={change('owner_name')} /></Field><Field icon={<Mail size={17} />} label="Owner email"><input required type="email" value={form.owner_email} onChange={change('owner_email')} /></Field><Field icon={<LockKeyhole size={17} />} label="Password"><input required minLength={8} type="password" value={form.password} onChange={change('password')} /></Field><Field icon={<LockKeyhole size={17} />} label="Confirm password"><input required minLength={8} type="password" value={form.password_confirmation} onChange={change('password_confirmation')} /></Field>{error && <p className="form-error">{error}</p>}<button className="button button-primary button-full" disabled={submitting}>{submitting ? 'Creating workspace…' : 'Create restaurant workspace'}</button><p className="auth-footer">Already have an account? <Link to="/login">Sign in</Link></p></form></AuthLayout>
}

function AuthLayout({ title, text, children }: { title: string; text: string; children: React.ReactNode }) { return <main className="auth-page"><section className="auth-aside"><div className="brand"><span className="brand-mark"><img src="/icon-192.png" alt="" width="32" height="32" /></span><span><strong>DineSetu</strong><small>Restaurant management</small></span></div><div><p className="eyebrow">HOSPITALITY, SIMPLIFIED</p><h1>Every table,<br />perfectly in flow.</h1><p>Fast restaurant operations for your floor, kitchen and counter.</p></div></section><section className="auth-card"><div className="auth-card-inner"><p className="eyebrow">DINESETU</p><h1>{title}</h1><p>{text}</p>{children}</div></section></main> }
function Field({ icon, label, children }: { icon: React.ReactNode; label: string; children: React.ReactNode }) { return <label className="field"><span>{icon}{label}</span>{children}</label> }
function CheckIcon() { return <span aria-hidden="true">✓</span> }
