import { CirclePlus, CookingPot, PackagePlus, Pencil, Search, UtensilsCrossed } from 'lucide-react'
import { useCallback, useEffect, useState } from 'react'
import type { FormEvent, InputHTMLAttributes, ReactNode, SelectHTMLAttributes } from 'react'
import { useSearchParams } from 'react-router-dom'
import { useAuth } from '../features/auth/AuthContext'
import { can } from '../features/auth/permissions'
import { api, errorMessage } from '../lib/api'
import type { ApiEnvelope, Category, KitchenStation, Outlet, Paginated, Product } from '../types/api'
import { money } from './opsShared'

function Heading({ eyebrow, title, text, action }: { eyebrow: string; title: string; text: string; action?: ReactNode }) { return <section className="page-heading"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{text}</p></div>{action}</section> }

export function MenuPage() {
  const { session } = useAuth(); const manage = can(session, 'catalog.manage'); const [categories, setCategories] = useState<Category[]>([]); const [stations, setStations] = useState<KitchenStation[]>([]); const [products, setProducts] = useState<Product[]>([]); const [outlets, setOutlets] = useState<Outlet[]>([]); const [error, setError] = useState(''); const [success, setSuccess] = useState(''); const [panel, setPanel] = useState<'product' | 'category' | 'station' | null>(null); const [editing, setEditing] = useState<Product | null>(null); const [params] = useSearchParams(); const [query, setQuery] = useState(params.get('q') ?? '')
  const load = useCallback(async () => { try { const [categoryData, stationData, productData] = await Promise.all([api.get<ApiEnvelope<Category[]>>('/api/v1/categories'), api.get<ApiEnvelope<KitchenStation[]>>('/api/v1/kitchen-stations'), api.get<Paginated<Product>>('/api/v1/products?per_page=100')]); setCategories(categoryData.data.data); setStations(stationData.data.data); setProducts(productData.data.data); if (can(session, 'settings.manage')) { const outletData = await api.get<ApiEnvelope<Outlet[]>>('/api/v1/outlets'); setOutlets(outletData.data.data) } } catch (err) { setError(errorMessage(err)) } }, [session])
  useEffect(() => { const task = window.setTimeout(() => { void load() }, 0); return () => window.clearTimeout(task) }, [load])
  async function saveProduct(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const values = new FormData(form); const fulfillmentMode = String(values.get('fulfillment_mode') || 'direct') as 'kitchen' | 'direct'; const data = { name: String(values.get('name')), short_description: String(values.get('short_description') || '') || null, serving_size: String(values.get('serving_size') || '') || null, category_id: values.get('category_id') ? Number(values.get('category_id')) : null, fulfillment_mode: fulfillmentMode, kitchen_station_id: fulfillmentMode === 'kitchen' && values.get('kitchen_station_id') ? Number(values.get('kitchen_station_id')) : null, selling_price: Number(values.get('selling_price')), cost_price: Number(values.get('cost_price') || 0), tax_rate: Number(values.get('tax_rate') || 0), sku: String(values.get('sku') || '') || null, barcode: String(values.get('barcode') || '') || null, hsn_code: String(values.get('hsn_code') || '') || null, track_inventory: values.has('track_inventory'), is_active: values.has('is_active') }; setError(''); try { if (editing) await api.put(`/api/v1/products/${editing.id}`, data); else await api.post('/api/v1/products', data); form.reset(); setPanel(null); setEditing(null); setSuccess(editing ? 'Product updated.' : 'Product added.'); await load() } catch (err) { setError(errorMessage(err)) } }
  async function saveCategory(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; try { await api.post('/api/v1/categories', { name: String(new FormData(form).get('name')) }); form.reset(); setPanel(null); setSuccess('Category added.'); await load() } catch (err) { setError(errorMessage(err)) } }
  async function saveStation(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const data = Object.fromEntries(new FormData(form)); try { await api.post('/api/v1/kitchen-stations', data); form.reset(); setPanel(null); setSuccess('Kitchen station added.'); await load() } catch (err) { setError(errorMessage(err)) } }
  const filtered = products.filter((product) => `${product.name} ${product.sku ?? ''} ${product.barcode ?? ''}`.toLowerCase().includes(query.toLowerCase()))
  return <><Heading eyebrow="CATALOG" title="Menu & products" text="Keep prices, tax and kitchen routing accurate. Inventory tracking is optional and never blocks orders." action={manage ? <div className="heading-actions"><button className="button button-secondary" onClick={() => setPanel('category')}><CirclePlus size={16} />Category</button>{outlets.length > 0 && <button className="button button-secondary" onClick={() => setPanel('station')}><CookingPot size={16} />Station</button>}<button className="button button-primary" onClick={() => { setEditing(null); setPanel('product') }}><PackagePlus size={16} />Add product</button></div> : undefined} />
    {panel === 'product' && <form className="settings-card compact-form" onSubmit={saveProduct}>
      <div className="role-form-heading"><div><h2>{editing ? `Edit ${editing.name}` : 'Add product'}</h2><p>Prices and tax are saved securely by the server.</p></div><button type="button" className="button button-secondary" onClick={() => { setPanel(null); setEditing(null) }}>Cancel</button></div>
      <div className="form-grid">
        <Field label="Product name" name="name" defaultValue={editing?.name} required />
        <Field label="Serving size / quantity" name="serving_size" placeholder="e.g. 20 ml, 100 ml, 500 g" defaultValue={editing?.serving_size ?? ''} />
        <Field label="Short description" name="short_description" placeholder="Shown to staff when ordering" defaultValue={editing?.short_description ?? ''} />
        <Field label="Selling price" name="selling_price" type="number" min="0" step="0.01" defaultValue={editing?.selling_price} required />
        <Field label="Cost price" name="cost_price" type="number" min="0" step="0.01" defaultValue={editing?.cost_price ?? '0'} />
        <Field label="Tax rate (%)" name="tax_rate" type="number" min="0" max="100" step="0.01" defaultValue={editing?.tax_rate ?? '0'} />
        <Field label="SKU" name="sku" defaultValue={editing?.sku ?? ''} />
        <Field label="Barcode" name="barcode" defaultValue={editing?.barcode ?? ''} />
        <Field label="HSN / SAC code" name="hsn_code" defaultValue={editing?.hsn_code ?? ''} />
        <Select label="Category" name="category_id" defaultValue={editing?.category_id ?? ''}><option value="">No category</option>{categories.filter((item) => item.is_active).map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</Select>
        <Select label="Service route" name="fulfillment_mode" defaultValue={editing?.fulfillment_mode ?? 'direct'}><option value="direct">Direct service — waiter collects it</option><option value="kitchen">Kitchen preparation</option></Select>
        <Select label="Kitchen station (required for kitchen items)" name="kitchen_station_id" defaultValue={editing?.kitchen_station_id ?? ''}><option value="">Select kitchen station</option>{stations.filter((item) => item.is_active).map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</Select>
      </div>
      <div className="check-group"><label className="check-row"><input type="checkbox" name="track_inventory" defaultChecked={editing?.track_inventory ?? false} />Track inventory (optional — never blocks taking or serving orders)</label><label className="check-row"><input type="checkbox" name="is_active" defaultChecked={editing?.is_active ?? true} />Available to sell</label></div>
      <button className="button button-primary">{editing ? 'Save product' : 'Add product'}</button>
    </form>}
    {panel === 'category' && <form className="settings-card compact-form inline-create" onSubmit={saveCategory}><Field label="Category name" name="name" required /><button className="button button-primary">Save category</button></form>}
    {panel === 'station' && <form className="settings-card compact-form inline-create" onSubmit={saveStation}><Field label="Station name" name="name" required /><Field label="Station code" name="code" required /><Select label="Outlet" name="outlet_id" defaultValue=""><option value="" disabled>Select outlet</option>{outlets.filter((outlet) => outlet.is_active).map((outlet) => <option key={outlet.id} value={outlet.id}>{outlet.name}</option>)}</Select><button className="button button-primary">Save station</button></form>}
    {error && <p className="form-error form-notice">{error}</p>}{success && <p className="form-success form-notice">{success}</p>}
    <section className="catalog-summary"><div><strong>{products.length}</strong><span>Products</span></div><div><strong>{categories.length}</strong><span>Categories</span></div><div><strong>{stations.length}</strong><span>Kitchen stations</span></div></section><label className="catalog-search"><Search size={17} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search by name, SKU or barcode" /></label><section className="product-grid">{filtered.map((product) => <article className="product-card" key={product.id}><div className="product-card-top"><span className="product-icon"><UtensilsCrossed size={20} /></span><span className={product.is_active ? 'status-badge status-green' : 'status-badge status-red'}>{product.is_active ? 'Active' : 'Inactive'}</span></div><h2>{product.name}{product.serving_size && <small> · {product.serving_size}</small>}</h2>{product.short_description && <p>{product.short_description}</p>}<p>{product.category?.name ?? 'Uncategorized'} · {product.fulfillment_mode === 'kitchen' ? `Kitchen · ${product.kitchen_station?.name ?? 'Station required'}` : 'Direct service'}</p><strong className="product-price">{money(product.selling_price, session?.hotel.currency_code)}</strong><small>Tax {product.tax_rate}% · {product.track_inventory ? 'Inventory tracked' : 'No inventory tracking'}</small>{manage && <button className="text-action" onClick={() => { setEditing(product); setPanel('product') }}><Pencil size={14} />Edit product</button>}</article>)}{!filtered.length && <p className="empty-row">No products found.</p>}</section></>
}

function Field({ label, ...props }: { label: string } & InputHTMLAttributes<HTMLInputElement>) { return <label className="field"><span>{label}</span><input {...props} /></label> }
function Select({ label, children, ...props }: { label: string; children: ReactNode } & SelectHTMLAttributes<HTMLSelectElement>) { return <label className="field"><span>{label}</span><select {...props}>{children}</select></label> }
